"""Initial migration

Revision ID: ea1a41d100ac
Revises: 
Create Date: 2025-11-23 01:23:09.528312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1a41d100ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('tokens_remaining', sa.Integer(), nullable=True),
    sa.Column('tokens_total', sa.Integer(), nullable=True),
    sa.Column('last_token_reset', sa.DateTime(), nullable=True),
    sa.Column('next_token_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('article_url', sa.Text(), nullable=False),
    sa.Column('published_time', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('view', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_scraped_at'), 'articles', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_articles_source'), 'articles', ['source'], unique=False)
    op.create_index(op.f('ix_articles_user_id'), 'articles', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_task_id'), 'jobs', ['task_id'], unique=True)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('user_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled_sites', sa.JSON(), nullable=True),
    sa.Column('scraper_schedule_enabled', sa.Boolean(), nullable=True),
    sa.Column('scraper_schedule_interval', sa.Integer(), nullable=True),
    sa.Column('allowed_formats', sa.JSON(), nullable=True),
    sa.Column('preferred_provider', sa.String(length=50), nullable=True),
    sa.Column('preferred_model', sa.String(length=100), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_configs_id'), 'user_configs', ['id'], unique=False)
    op.create_index(op.f('ix_user_configs_user_id'), 'user_configs', ['user_id'], unique=True)
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_article_id'), 'translations', ['article_id'], unique=False)
    op.create_index(op.f('ix_translations_created_at'), 'translations', ['created_at'], unique=False)
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    op.create_index(op.f('ix_translations_user_id'), 'translations', ['user_id'], unique=False)
    op.create_table('enhancements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('format_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enhancements_created_at'), 'enhancements', ['created_at'], unique=False)
    op.create_index(op.f('ix_enhancements_format_type'), 'enhancements', ['format_type'], unique=False)
    op.create_index(op.f('ix_enhancements_id'), 'enhancements', ['id'], unique=False)
    op.create_index(op.f('ix_enhancements_translation_id'), 'enhancements', ['translation_id'], unique=False)
    op.create_index(op.f('ix_enhancements_user_id'), 'enhancements', ['user_id'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('translation_id', sa.Integer(), nullable=True),
    sa.Column('enhancement_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enhancement_id'], ['enhancements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_id'), 'token_usage', ['id'], unique=False)
    op.create_index(op.f('ix_token_usage_operation'), 'token_usage', ['operation'], unique=False)
    op.create_index(op.f('ix_token_usage_timestamp'), 'token_usage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_token_usage_user_id'), 'token_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usage_user_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_timestamp'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_operation'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_id'), table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index(op.f('ix_enhancements_user_id'), table_name='enhancements')
    op.drop_index(op.f('ix_enhancements_translation_id'), table_name='enhancements')
    op.drop_index(op.f('ix_enhancements_id'), table_name='enhancements')
    op.drop_index(op.f('ix_enhancements_format_type'), table_name='enhancements')
    op.drop_index(op.f('ix_enhancements_created_at'), table_name='enhancements')
    op.drop_table('enhancements')
    op.drop_index(op.f('ix_translations_user_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_created_at'), table_name='translations')
    op.drop_index(op.f('ix_translations_article_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_user_configs_user_id'), table_name='user_configs')
    op.drop_index(op.f('ix_user_configs_id'), table_name='user_configs')
    op.drop_table('user_configs')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_task_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_articles_user_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_source'), table_name='articles')
    op.drop_index(op.f('ix_articles_scraped_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
